```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(data.table)
library(sf)
library(ggplot2)
library(ggsflabel)
library(ggspatial)
library(knitr)
library(kableExtra)
library(TDX)
library(DT)

Sys.setlocale(category = "LC_ALL", locale = "zh_TW.UTF-8")

windowsFonts(A=windowsFont("微軟正黑體"))

client_id=read.csv("./key.txt", header=F)[1,2]
client_secret=read.csv("./key.txt", header=F)[2,2]
access_token=get_token(client_id, client_secret)
```

# **R 語言基礎語法**
本章節系統性介紹 R 語言的重要語法和`dplyr`套件的功能及用法，請務必熟悉各函式，以便後續程式碼撰寫。  

## 物件（Object）
物件是 R 語言中構成資料的基本要素，常見者包含五大類：  

1.  向量（vector）  
2.  層級（factor）  
3.  矩陣（matrix）   
4.  資料框（data frame）  
5.  陣列（list）  


### 向量
<p style="color:#003D79;font-size:18px;line-height:2">**⌾ 向量特徵**</p>  

* 一組值  
* 一維  
* 資料型態可為：數值、文字、邏輯值  

<p style="color:#003D79;font-size:18px;line-height:2">**⌾ 利用`c()` 建立向量**</p>  

* **數值向量**
```{r vector1, echo=T, eval=F}
vec1=c(1,2,3,4,5)
```

```{r vector1-show, echo=F, eval=T}
vec1=c(1,2,3,4,5)
vec1
```

* **文字向量**
```{r vector2, echo=T, eval=F}
vec2=c("A","B","C","D","E")
```

```{r vector2-show, echo=F, eval=T}
vec2=c("A","B","C","D","E")
vec2
```

* **邏輯向量**
```{r vector3, echo=T, eval=F}
vec3=c(T,F,T,F,T)
```


<p style="color:#003D79;font-size:18px;line-height:2">**⌾ 擷取特定向量中特定元素**</p>  

* **在`vec2`中擷取第三個元素**
```{r vector-retrieve1, echo=T, eval=T}
vec2[3]
```

* **在`vec2`中擷取多個連續元素**
```{r vector-retrieve2, echo=T, eval=T}
vec2[2:4]
```

* **在`vec2`中擷取多個非連續元素**
```{r vector-retrieve3, echo=T, eval=T}
vec2[c(1,3,5)]
```

<p style="color:#003D79;font-size:18px;line-height:2">**⌾ 建立連續數值資料**</p> 

```{r vector-continuous1, echo=T, eval=T}
seq(from=2, to=20, by=2)
```

<p style="color:#003D79;font-size:18px;line-height:2">**⌾ 向量運算**</p>  

先行建立一個向量`vec4`。
```{r vector-exg, echo=T, eval=T}
vec4=c(1,9,3,15,6,2,8,12)
```

所有運算的程式碼與結果請參照表\@ref(tab:vector-operation-table)。

```{r vector-operation-table, echo=F, eval=T}
vector_operation=data.frame(ope_name=c("最大值","最小值","全域","總和","平均","中位數","乘積","變異數","標準差"), operation=c("`max(vec4)`","`min(vec4)`","`range(vec4)`","`sum(vec4)`","`mean(vec4)`","`median(vec4)`","`prod(vec4)`","`var(vec4)`","`sd(vec4)`"),
                         result=c(paste0("`", max(vec4), "`"), paste0("`", min(vec4), "`"), paste0("`", paste(range(vec4), collapse="  "), "`"), paste0("`", sum(vec4), "`"), paste0("`", mean(vec4), "`"), paste0("`", median(vec4), "`"), paste0("`", prod(vec4), "`"), paste0("`", round(var(vec4), 3), "`"), paste0("`", round(sd(vec4), 3), "`")))

colnames(vector_operation)=c("運算","程式碼","輸出結果")
kable(vector_operation, booktabs=T, caption="向量運算")%>%
  kable_styling(bootstrap_options=c("striped", "hover"), font_size=14)%>%
  column_spec(1, bold=T)%>%
  row_spec(0, bold=T, color="white", background="#8E8E8E")
```




